// // Copyright 2022 Mindbox Ltd
// //
// // Licensed under the Apache License, Version 2.0 (the "License");
// // you may not use this file except in compliance with the License.
// // You may obtain a copy of the License at
// //
// //     http://www.apache.org/licenses/LICENSE-2.0
// //
// // Unless required by applicable law or agreed to in writing, software
// // distributed under the License is distributed on an "AS IS" BASIS,
// // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// // See the License for the specific language governing permissions and
// // limitations under the License.

using System;
using System.Collections.Generic;

namespace Mindbox.Quokka
{
	internal static class CurrencyFormats
	{
		private static readonly IReadOnlyDictionary<string, CurrencyFormat> formatsByCode =
			new Dictionary<string, CurrencyFormat>(StringComparer.OrdinalIgnoreCase)
			{
				["AED"] = new("AED", "AED", 2, spaceAfterSymbol: true),
				["AFN"] = new("؋", "AFN", 0),
				["ALL"] = new("ALL", "ALL", 0, spaceAfterSymbol: true),
				["AMD"] = new("֏", "AMD", 2),
				["ANG"] = new("ANG", "ANG", 2, spaceAfterSymbol: true),
				["AOA"] = new("Kz", "AOA", 2, spaceAfterSymbol: true),
				["ARS"] = new("$", "ARS", 2),
				["AUD"] = new("$", "A$", 2),
				["AWG"] = new("AWG", "AWG", 2, spaceAfterSymbol: true),
				["AZN"] = new("₼", "AZN", 2),
				["BAM"] = new("KM", "BAM", 2, spaceAfterSymbol: true),
				["BBD"] = new("$", "BBD", 2),
				["BDT"] = new("৳", "BDT", 2),
				["BGN"] = new("BGN", "BGN", 2, spaceAfterSymbol: true),
				["BHD"] = new("BHD", "BHD", 3, spaceAfterSymbol: true),
				["BIF"] = new("BIF", "BIF", 0, spaceAfterSymbol: true),
				["BMD"] = new("$", "BMD", 2),
				["BND"] = new("$", "BND", 2),
				["BOB"] = new("Bs", "BOB", 2, spaceAfterSymbol: true),
				["BRL"] = new("R$", "R$", 2),
				["BSD"] = new("$", "BSD", 2),
				["BTN"] = new("BTN", "BTN", 2, spaceAfterSymbol: true),
				["BWP"] = new("P", "BWP", 2, spaceAfterSymbol: true),
				["BYN"] = new("BYN", "BYN", 2, spaceAfterSymbol: true),
				["BZD"] = new("$", "BZD", 2),
				["CAD"] = new("$", "CA$", 2),
				["CDF"] = new("CDF", "CDF", 2, spaceAfterSymbol: true),
				["CHF"] = new("CHF", "CHF", 2, spaceAfterSymbol: true),
				["CLP"] = new("$", "CLP", 0),
				["CNY"] = new("¥", "CN¥", 2),
				["COP"] = new("$", "COP", 0),
				["CRC"] = new("₡", "CRC", 2),
				["CVE"] = new("CVE", "CVE", 2, spaceAfterSymbol: true),
				["CZK"] = new("Kč", "CZK", 2, spaceAfterSymbol: true),
				["DJF"] = new("DJF", "DJF", 0, spaceAfterSymbol: true),
				["DKK"] = new("kr", "DKK", 2, spaceAfterSymbol: true),
				["DOP"] = new("$", "DOP", 2),
				["DZD"] = new("DZD", "DZD", 2, spaceAfterSymbol: true),
				["EGP"] = new("E£", "EGP", 2),
				["ERN"] = new("ERN", "ERN", 2, spaceAfterSymbol: true),
				["ETB"] = new("ETB", "ETB", 2, spaceAfterSymbol: true),
				["EUR"] = new("€", "€", 2),
				["FJD"] = new("$", "FJD", 2),
				["FKP"] = new("£", "FKP", 2),
				["GBP"] = new("£", "£", 2),
				["GEL"] = new("₾", "GEL", 2),
				["GHS"] = new("GH₵", "GHS", 2),
				["GIP"] = new("£", "GIP", 2),
				["GMD"] = new("GMD", "GMD", 2, spaceAfterSymbol: true),
				["GNF"] = new("FG", "GNF", 0, spaceAfterSymbol: true),
				["GTQ"] = new("Q", "GTQ", 2, spaceAfterSymbol: true),
				["GYD"] = new("$", "GYD", 2),
				["HKD"] = new("$", "HK$", 2),
				["HNL"] = new("L", "HNL", 2, spaceAfterSymbol: true),
				["HTG"] = new("HTG", "HTG", 2, spaceAfterSymbol: true),
				["HUF"] = new("Ft", "HUF", 0, spaceAfterSymbol: true),
				["IDR"] = new("Rp", "IDR", 0, spaceAfterSymbol: true),
				["ILS"] = new("₪", "₪", 2),
				["INR"] = new("₹", "₹", 2),
				["IQD"] = new("IQD", "IQD", 0, spaceAfterSymbol: true),
				["IRR"] = new("IRR", "IRR", 0, spaceAfterSymbol: true),
				["ISK"] = new("kr", "ISK", 0, spaceAfterSymbol: true),
				["JEP"] = new("JEP", "JEP", 2, spaceAfterSymbol: true),
				["JMD"] = new("$", "JMD", 2),
				["JOD"] = new("JOD", "JOD", 3, spaceAfterSymbol: true),
				["JPY"] = new("¥", "JP¥", 0),
				["KES"] = new("KES", "KES", 2, spaceAfterSymbol: true),
				["KGS"] = new("⃀", "KGS", 2),
				["KHR"] = new("៛", "KHR", 2),
				["KMF"] = new("CF", "KMF", 0, spaceAfterSymbol: true),
				["KRW"] = new("₩", "₩", 0),
				["KWD"] = new("KWD", "KWD", 3, spaceAfterSymbol: true),
				["KYD"] = new("$", "KYD", 2),
				["KZT"] = new("₸", "KZT", 2),
				["LAK"] = new("₭", "LAK", 0),
				["LBP"] = new("L£", "LBP", 0),
				["LKR"] = new("Rs", "LKR", 2, spaceAfterSymbol: true),
				["LRD"] = new("$", "LRD", 2),
				["LSL"] = new("LSL", "LSL", 2, spaceAfterSymbol: true),
				["LYD"] = new("LYD", "LYD", 3, spaceAfterSymbol: true),
				["MAD"] = new("MAD", "MAD", 2, spaceAfterSymbol: true),
				["MDL"] = new("MDL", "MDL", 2, spaceAfterSymbol: true),
				["MGA"] = new("Ar", "MGA", 0, spaceAfterSymbol: true),
				["MKD"] = new("MKD", "MKD", 2, spaceAfterSymbol: true),
				["MMK"] = new("K", "MMK", 0, spaceAfterSymbol: true),
				["MNT"] = new("₮", "MNT", 2),
				["MOP"] = new("MOP", "MOP", 2, spaceAfterSymbol: true),
				["MRU"] = new("MRU", "MRU", 2, spaceAfterSymbol: true),
				["MUR"] = new("Rs", "MUR", 2, spaceAfterSymbol: true),
				["MVR"] = new("MVR", "MVR", 2, spaceAfterSymbol: true),
				["MWK"] = new("MWK", "MWK", 2, spaceAfterSymbol: true),
				["MXN"] = new("$", "MX$", 2),
				["MYR"] = new("RM", "MYR", 2, spaceAfterSymbol: true),
				["MZN"] = new("MZN", "MZN", 2, spaceAfterSymbol: true),
				["NAD"] = new("$", "NAD", 2),
				["NGN"] = new("₦", "NGN", 2),
				["NIO"] = new("C$", "NIO", 2),
				["NOK"] = new("kr", "NOK", 2, spaceAfterSymbol: true),
				["NPR"] = new("Rs", "NPR", 2, spaceAfterSymbol: true),
				["NZD"] = new("$", "NZ$", 2),
				["OMR"] = new("OMR", "OMR", 3, spaceAfterSymbol: true),
				["PAB"] = new("PAB", "PAB", 2, spaceAfterSymbol: true),
				["PEN"] = new("PEN", "PEN", 2, spaceAfterSymbol: true),
				["PGK"] = new("PGK", "PGK", 2, spaceAfterSymbol: true),
				["PHP"] = new("₱", "₱", 2),
				["PKR"] = new("Rs", "PKR", 0, spaceAfterSymbol: true),
				["PLN"] = new("zł", "PLN", 2, spaceAfterSymbol: true),
				["PYG"] = new("₲", "PYG", 0),
				["QAR"] = new("QAR", "QAR", 2, spaceAfterSymbol: true),
				["RON"] = new("lei", "RON", 2, spaceAfterSymbol: true),
				["RSD"] = new("RSD", "RSD", 2, spaceAfterSymbol: true),
				["RUB"] = new("₽", "RUB", 2),
				["RWF"] = new("RF", "RWF", 0, spaceAfterSymbol: true),
				["SAR"] = new("SAR", "SAR", 2, spaceAfterSymbol: true),
				["SBD"] = new("$", "SBD", 2),
				["SCR"] = new("SCR", "SCR", 2, spaceAfterSymbol: true),
				["SDG"] = new("SDG", "SDG", 2, spaceAfterSymbol: true),
				["SEK"] = new("kr", "SEK", 2, spaceAfterSymbol: true),
				["SGD"] = new("$", "SGD", 2),
				["SHP"] = new("£", "SHP", 2),
				["SLL"] = new("SLL", "SLL", 0, spaceAfterSymbol: true),
				["SOS"] = new("SOS", "SOS", 0, spaceAfterSymbol: true),
				["SRD"] = new("$", "SRD", 2),
				["SSP"] = new("£", "SSP", 2),
				["STN"] = new("Db", "STN", 2, spaceAfterSymbol: true),
				["SYP"] = new("£", "SYP", 0),
				["SZL"] = new("SZL", "SZL", 2, spaceAfterSymbol: true),
				["THB"] = new("฿", "THB", 2),
				["TJS"] = new("TJS", "TJS", 2, spaceAfterSymbol: true),
				["TMT"] = new("TMT", "TMT", 2, spaceAfterSymbol: true),
				["TND"] = new("TND", "TND", 3, spaceAfterSymbol: true),
				["TOP"] = new("T$", "TOP", 2),
				["TRY"] = new("₺", "TRY", 2),
				["TTD"] = new("$", "TTD", 2),
				["TWD"] = new("$", "NT$", 2),
				["TZS"] = new("TZS", "TZS", 2, spaceAfterSymbol: true),
				["UAH"] = new("₴", "UAH", 2),
				["UGX"] = new("UGX", "UGX", 0, spaceAfterSymbol: true),
				["USD"] = new("$", "US$", 2),
				["UYU"] = new("$", "UYU", 2),
				["UZS"] = new("UZS", "UZS", 2, spaceAfterSymbol: true),
				["VES"] = new("VES", "VES", 2, spaceAfterSymbol: true),
				["VND"] = new("₫", "₫", 0),
				["VUV"] = new("VUV", "VUV", 0, spaceAfterSymbol: true),
				["WST"] = new("WST", "WST", 2, spaceAfterSymbol: true),
				["XAF"] = new("FCFA", "FCFA", 0, spaceAfterSymbol: true),
				["XCD"] = new("$", "EC$", 2),
				["XOF"] = new("F CFA", "F CFA", 0, spaceAfterSymbol: true),
				["XPF"] = new("CFPF", "CFPF", 0, spaceAfterSymbol: true),
				["YER"] = new("YER", "YER", 0, spaceAfterSymbol: true),
				["ZAR"] = new("R", "ZAR", 2, spaceAfterSymbol: true),
				["ZMW"] = new("ZK", "ZMW", 2, spaceAfterSymbol: true)
			};

		public static CurrencyFormat TryGet(string currencyCode) =>
			currencyCode != null && formatsByCode.TryGetValue(currencyCode, out var format)
				? format
				: null;
	}
}
