// Regenerates Engine/Quokka.Core/Functions/Standard/Money/CurrencyFormats.g.cs from the CLDR
// data vendored in ./cldr. Run `node generate.mjs`; it needs nothing but Node.
// The output is committed; CI re-runs this and fails if the committed file differs.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const LOCALE = 'en-001';
const OUTPUT = path.resolve(here, '../../Engine/Quokka.Core/Functions/Standard/Money/CurrencyFormats.g.cs');

const read = name => JSON.parse(fs.readFileSync(path.resolve(here, 'cldr', name), 'utf8'));

const symbols = read('currencies-en-001.json').main[LOCALE].numbers.currencies;
const fractions = read('currencyData.json').supplemental.currencyData.fractions;
const decimalPlacesOf = code => Number((fractions[code] ?? fractions.DEFAULT)._digits);
const escape = value => value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

const entries = [];
for (const code of Object.keys(symbols).sort()) {
	const entry = symbols[code];
	const symbol = entry.symbol ?? code;
	const narrow = entry['symbol-alt-narrow'] ?? symbol;
	const decimals = decimalPlacesOf(code);
	entries.push(`\t\t\t\t["${code}"] = new("${escape(narrow)}", "${escape(symbol)}", ${decimals}),`);
}

if (entries.length === 0)
	throw new Error('CLDR produced no currencies — refusing to write an empty table');

entries[entries.length - 1] = entries.at(-1).replace(/,$/, '');

const cldrVersion = fs.readFileSync(path.resolve(here, 'cldr/VERSION'), 'utf8').trim();
const source = `// // Copyright 2022 Mindbox Ltd
// //
// // Licensed under the Apache License, Version 2.0 (the "License");
// // you may not use this file except in compliance with the License.
// // You may obtain a copy of the License at
// //
// //     http://www.apache.org/licenses/LICENSE-2.0
// //
// // Unless required by applicable law or agreed to in writing, software
// // distributed under the License is distributed on an "AS IS" BASIS,
// // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// // See the License for the specific language governing permissions and
// // limitations under the License.

// <auto-generated>
//     Generated by tools/currency-table from CLDR ${cldrVersion} (${LOCALE}). Do not edit by hand.
// </auto-generated>

using System;
using System.Collections.Generic;

namespace Mindbox.Quokka
{
\tinternal static class CurrencyFormats
\t{
\t\tprivate static readonly IReadOnlyDictionary<string, CurrencyFormat> formatsByCode =
\t\t\tnew Dictionary<string, CurrencyFormat>(StringComparer.OrdinalIgnoreCase)
\t\t\t{
${entries.join('\n')}
\t\t\t};

\t\tpublic static CurrencyFormat TryGet(string currencyCode) =>
\t\t\tcurrencyCode != null && formatsByCode.TryGetValue(currencyCode, out var format)
\t\t\t\t? format
\t\t\t\t: null;
\t}
}
`;

fs.writeFileSync(OUTPUT, source);
console.log(`wrote ${entries.length} currencies from CLDR ${cldrVersion}`);
