name: release

on: 
    push:
        branches:
            - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Check License Lines
      uses: kt3k/license_checker@v1.0.6
      
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9

    - name: Build
      run: dotnet build Engine/Quokka.slnx --configuration Release
      
    - name: Test
      run: dotnet test Engine/Quokka.slnx --no-build --configuration Release
      
    - name: Pack
      run: dotnet pack Engine/Quokka.slnx -c Release

    - name: Publish
      run: dotnet nuget push **/*.nupkg -k ${{secrets.MINDBOX_NUGET_AUTH_TOKEN}} -s https://www.nuget.org/api/v2/package
